default_login:
    path: /login
    defaults: { _controller:AppBundle:Default:login}
    methods: [POST]
default_registro:
    path: /usuario/new
    defaults: { _controller:AppBundle:Default:register}
    methods: [POST]
